# Generated by Django 5.2.6 on 2025-09-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0002_auto_20250904_1252"),
    ]

    operations = [
        migrations.AddField(
            model_name="famousathlete",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="famousathlete",
            name="birthdate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="famousathlete",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="famousathlete",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="famousathlete",
            name="records",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="famousathlete",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sport",
            name="first_appearance",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sport",
            name="governing_body",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sport",
            name="number_of_players",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sport",
            name="origin_country",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sport",
            name="team_sport",
            field=models.BooleanField(default=False),
        ),
    ]
