# Generated by Django 5.2.6 on 2025-09-29 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_famousathlete_active_famousathlete_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('year_set', models.IntegerField(blank=True, null=True)),
                ('still_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_set', to='sports.famousathlete')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sports.sport')),
            ],
        ),
    ]
